//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.09 at 11:35:14 AM BRT 
//


package br.com.miguelprogrammer;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.miguelprogrammer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.miguelprogrammer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCostumerDetailRequest }
     * 
     */
    public GetCostumerDetailRequest createGetCostumerDetailRequest() {
        return new GetCostumerDetailRequest();
    }

    /**
     * Create an instance of {@link GetCostumerDetailResponse }
     * 
     */
    public GetCostumerDetailResponse createGetCostumerDetailResponse() {
        return new GetCostumerDetailResponse();
    }

    /**
     * Create an instance of {@link CostumerDetail }
     * 
     */
    public CostumerDetail createCostumerDetail() {
        return new CostumerDetail();
    }

    /**
     * Create an instance of {@link GetAllCostumerDetailResponse }
     * 
     */
    public GetAllCostumerDetailResponse createGetAllCostumerDetailResponse() {
        return new GetAllCostumerDetailResponse();
    }

}
